### ISSUE TITLE
Change initial population for puzzle 2

### ISSUE THREAD

**Issue by Hoangngo-dev** [sdnorton/AI15_Assignment_2#3]
In the assignment, Prof Beck said:
`you may restrict initial members of the population (and crossovers) to having 10 numbers in each bin`

Thus we can change the constructor of `NumberAllocationMember` to do this.

**Comment by Hoangngo-dev** [comment]
I implemented it here https://github.com/sdnorton/AI15_Assignment_2/tree/features/init-pop-puzzle-2

If we agree on this, we can merge to master branch

**Comment by sdnorton** [comment]
I like it. Sorry, I was only checking trello for issues. But yeah, I'll merge it in when I'm coalescing code tonight.
